resume delete,patch,list api and their test.py
wecode-bootcamp-korea/30-2nd-WantU-backend pull request #10
Opened 2022-03-20 08:45 UTC by YEONG-CTRL

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 이력서 이름변경 , 삭제 , 이력서 리스트 API 및 그것들의 테스트코드

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Patch를 사용하여 이력서의 이름을 변경하는 기능을 추가했습니다. filter로 패스 파라미터에 해당하는 이력서를 특정하고 , update메소드로 이름을 변경해주었습니다
2. delete를 사용하여 특정 이력서를 삭제합니다. 이때 delete_object 메소드를 이용하여 s3의 객체도 삭제하여 줍니다 
3. 이력서 리스트 페이지에 맞는 데이터를 뿌려주는 ResumeListView를 작성했습니다 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-21 01:43 UTC, kyeongraekim requested changes

2022-03-21 01:43 UTC, kyeongraekim commented on cv/tests.py
> +            ]
test용 mock data를 만드실 때는 for문을 돌리는 것 보다 각각의 데이터 객체를 명확히 명시해주는게 제3자의 코드독해 및 추후 코드 확장성을 위해서 더 효율적입니다. 그 까닭은 각각의 개별 데이터 객체와 그 객체가 가지고 있는 모든 필드값요소에 대한 접근/수정/관리가 개발자에게 보다 용이해야되기 때문입니다. bulk_create는 잘 적용해주셨던데 해당 데이터를 다시 풀어서 써주세요~

2022-03-21 01:43 UTC, kyeongraekim commented on cv/tests.py
> +    def test_fail_changing_resume_name_dueto_wrong_invalid_resume_pk(self):
wrong_invalid 가 무언가 verbose 하게 느껴지네요~

2022-03-21 01:43 UTC, kyeongraekim commented on cv/tests.py
> +class ResumeInfoView(TestCase):
Test에 해당되는 View 이기때문에 View클래스 네이밍에도 테스트임을 암시하는 단어가 필요해보이네요~

2022-03-21 01:43 UTC, kyeongraekim commented on cv/views.py
> +            if resume:
존재유무를 판단하는 메소드인 .exists()를 쓰는게 더 효율적일 것 같네요~

2022-03-21 01:43 UTC, kyeongraekim commented on cv/views.py
> +    def delete(self,request,resume_pk): # 특정 이력서 삭제
뒤에 코드 독해로 충분히 파악이 가능한 불필요한 한글 주석은 삭제해주세요~

2022-03-21 01:43 UTC, kyeongraekim commented on cv/tests.py
> +    @classmethod
classmethod에 대한 역할과 기능을 아래 코멘트로 한 번 남겨주실 수 있으신가요? 그리고 classmethod와 항상 대비되어서 비교되는 staticmethod 에 대한 내용도 리서치 해보세요!~

2022-03-21 02:15 UTC, YEONG-CTRL commented on cv/views.py
> +            if resume:
resume 쿼리셋 전체를 evaluate 하는 if문(bool() 사용)으로 인해 불필요하게 전체 쿼리셋을 캐싱하는 것보다, exists()를 사용해서 쿼리셋 전체를 evaluate하지 않고 값이 1개이상 존재하는지만 확인하는게 낫다는 말씀으로 이해했습니다~ 수정했습니다

2022-03-21 02:44 UTC, YEONG-CTRL commented on cv/tests.py
> +    @classmethod
setup - teardown 에서 setUpTestData로 변경하면서 클래스 전반에 걸쳐서 초기에 클래스의 속성으로 데이터를 지정해줄 필요가 생겼습니다 (setUp의 경우 def 로 class의 인스턴스인 self를 상속받아서 데이터를 만드는것과 반대) 따라서 인스턴스를 만들지 않아도(self) 클래스의 메서드 및 속성에 접근할 수 있는 @classmethod를 사용하여 cls.~~ 의 형식으로 값을 지정해주었습니다. 이를 통해 클래스에 초기 데이터를 만들고, 이후 테스트함수에서 클래스를 상속받은 `self.header` 이런 형식으로 클래스에 있는 토큰값을 사용해서 로그인데코레이터 부분을 통과해주었습니다.

2022-03-21 04:41 UTC, kyeongraekim requested changes

2022-03-21 04:41 UTC, kyeongraekim commented on cv/views.py
> +        if resume:
이곳도 filter 메소드를 유지하실거라면 동일하게 exists()문을 추가할 수 있겠네요~

2022-03-21 04:41 UTC, kyeongraekim commented on cv/views.py
> +            return JsonResponse({'message': 'Invalid resume_pk'}, status=404)
**[접근 방향1]**
해당부분은 s3와 로컬 테이블에 각각 다른 시점에 접근을 함으로 transaction 사용이 필요시되어 보입니다~ 
filter로 판별 할 때와 달리, get으로 해당 객체를 잡고 로컬에서 delete를 하셔도 물려있는 객체의 인스턴스 정보에 접근이 가능한데, transaction을 걸 때, 아래의 순서로 한 번 진행해보는 것을 추천드립니다. 해당 이유는 트랜잭션 적용이 S3까지는 영향을 주지 못하는 관계로, 모든 상황이 완벽하게 진행됬을 때 가장 마지막에 해당 내용을 마지막으로 실행하려는 의도입니다.

`(1) transaction 선적용 -> (2) resume.get(id=resume_pk) 객체 잡기 -> (3) 해당 내용 로컬 디비에서 삭제 -> (4) 2번 단계에서  메모리에 저장된 객체 정보를 통해 얻은 데이터로 S3 업로드 내용 삭제 -> (5)get에 얽힐 수 있는 모델 인스턴스 doesnotexist exception 에러 핸들링`

**[접근 방향2]**
실제 상용화된 서비스에서는 무조건적인 hard delete가 아닌 soft delete 를 선 진행하고 일정시간이 진행되면 불필요한 파일에 대해서 일괄 삭제 작업을 할 것입니다. 이때는 별도의 S3 스케줄러 라는 개념이 적용됩니다. 실제 서비스의 느낌대로 가시고 싶으시다면 is_deleted  T/F 칼럼을 추가해주시고 소프트한 삭제로 전환해주세요~ 그리고 추후에 프로젝트 종료후 리팩토링 과제로 S3 스케줄러도 코드로 작성해보실 수 있겠네요. 다만 이미 아마존에서 기존에 제공하고 있는 기능이니 아마존에 대한 공부로 또 나아가실수 있겠습니다.

2022-03-21 04:41 UTC, kyeongraekim commented on cv/views.py
> +        resume = Resume.objects.filter(id=resume_pk)
resume_pk 값에 대해서는 uuid 값을 가지고 있는 부분이 있으니 객체도 uuid에 대한 접근으로 진행해주심을 권장드립니다~

2022-03-21 09:51 UTC, YEONG-CTRL commented on cv/views.py
> +            return JsonResponse({'message': 'Invalid resume_pk'}, status=404)
soft delete 이후 별도의 파이썬 파일에서 기한 지난 데이터 삭제해주는 방식으로 수정해서 push했습니다~!

2022-03-22 03:01 UTC, kyeongraekim requested changes

2022-03-22 03:01 UTC, kyeongraekim commented on cv/views.py
> +            "uuid"           : resume.uuid,
uuid 부분 정렬 한 번만 다시 봐주세요~

2022-03-22 03:01 UTC, kyeongraekim commented on delete_file.py
> +    filtered_resume = Resume.objects.all().filter(is_deleted=True, deleted_at__lte=month_ago)
objects. 바로다음에 all()호출 말고 바로 filter 메소드를 호출하는게 낫지 않을까요?

2022-03-22 03:01 UTC, kyeongraekim commented on delete_file.py
> +    filtered_resume = Resume.objects.all().filter(is_deleted=True, deleted_at__lte=month_ago)
objects. 바로다음에 all()호출 말고 바로 filter 메소드를 호출하는게 낫지 않을까요?

2022-03-22 03:01 UTC, kyeongraekim commented on delete_file.py
> +
별도의 파일로써 실행할 때 파이썬에셔 꼭 있어야 하는 main , name 관련 부분이 안보이네요!~

2022-03-22 03:01 UTC, kyeongraekim commented on delete_file.py
> +
별도의 파일로써 실행할 때 파이썬에셔 꼭 있어야 하는 main , name 관련 부분이 안보이네요!~

2022-03-22 03:05 UTC, kyeongraekim requested changes

2022-03-22 03:05 UTC, kyeongraekim commented on delete_file.py
> +
추가로 파일명을 s3_delete_outdated_file로 변경하면 좋을 것 같습니다!

2022-03-22 04:59 UTC, YEONG-CTRL commented on delete_file.py
> +
__name__ 변수는 현재 스크립트 파일이 변수의 시작점(파일 그대로 시작)했는지 - 이때는 __main__ , 혹은 모듈로써 사용했는지 확인하는 용도로 사용하는 것으로 알고 있습니다. 별도의 실행파일로 실행될때만 실행될수 있도록 `if __name__ == '__main__':` 으로 현재 파일이 프로그램의 시작점일때만 실행될 수 있도록 해주었습니다

2022-03-22 08:42 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-22 08:42 UTC, merged