[이예솔] 채용 공고 리스트, 상세 정보 api + 공고에 대한 유저 정보 api
wecode-bootcamp-korea/30-2nd-WantU-backend pull request #13
Opened 2022-03-22 14:01 UTC by wingna1

…sts.py

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 채용 공고 리스트
- 채용 공고 상세 정보
- 채용 공고에 대한 유저 정보
- 위 api에 대한 테스트 케이스

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 작업 중 프론트가 거의 완성되어 리스트와 상세 정보 api를 동시에 진행했습니다.

1. 채용 공고 리스트
- 페이징은 추가된다고 해서 주석이 남아있습니다.. 일단 다른 기능들을 리뷰받으려고 같이 PR 올립니다.
- Q객체 사용해 filter를 추가했습니다.

2. 채용 공고 상세 정보
- 패스 파라미터로 공고 id 받아 해당 공고에 대한 상세 정보 리턴
- tag와 image를 위해 각각 데이터 받으나 한 공고에 대한 데이터라 양이 적다

3. 채용 공고에 대한 유저 정보
- 사용자 id로 applicant에서 데이터를 찾아 해당 공고id에 대한 지원 내역을 찾아 boolean으로 리턴
- 지원하기 위한 이력서 리스트 리턴

4. 테스트 케이스 작성 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-23 05:42 UTC, kyeongraekim requested changes

2022-03-23 05:42 UTC, kyeongraekim commented on jobs/views.py
> +        # page        = request.GET.get("page")
주석 처리가 되어 있네요!~ 해당 내용 살릴 것인가, 남길 것인가 재 확인 한 번만 해주세요!~

2022-03-23 05:42 UTC, kyeongraekim commented on jobs/views.py
> +        whole_list = JobPosition.objects.select_related("company").prefetch_related("tagnotification_set").filter(q).order_by(sort)
sort에 해당되는 내용 dictionary 형태로 의도한 옵션 내용을 추가해주셔서 추후의 확장성과, 백엔드에서의 쿼리파라미터 정보 접근을 더 용이하게 수정해주세요!~

2022-03-23 05:48 UTC, wingna1 commented on jobs/views.py
> +        # page        = request.GET.get("page")
페이징이 프론트에서 추가될 내역이라 살릴 예정입니다!

2022-03-23 05:49 UTC, wingna1 commented on jobs/views.py
> +        whole_list = JobPosition.objects.select_related("company").prefetch_related("tagnotification_set").filter(q).order_by(sort)
옵션이 아예 컬럼명으로 전달되고 있어서 딕셔너리 형태로 적어두면 사용되지 않을 텐데 괜찮을까요??

2022-03-23 07:28 UTC, wingna1 commented
- tests.py에서 이력서의 created_at 리턴할 경우 시간이 달라 일어나던 문제 해결

2022-03-24 04:55 UTC, wingna1 commented
- 채용 공고 상세에 대한 user의 지원 정보와 이력서 리스트를 리턴할 때에 이력서 리스트 api와 통일하여 created_at에서 created_date로 수정
- 채용 공고 리스트 api에서 sort를 숫자로 받아 dict에 맞는 값을 사용해 정렬하도록 수정
- 채용 공고 리스트 api에서 필터링을 사용해 리스트를 받아올 때에 prefetch_related가 존재하는 것이 쿼리 수를 더 늘리므로 select_related만 남기고 삭제

 *** 채용 공고 목록을 리턴할 때에 페이징이 추가될 예정입니다

2022-03-24 07:44 UTC, kyeongraekim requested changes

2022-03-24 07:44 UTC, kyeongraekim commented on jobs/views.py
> +                "5":"-id"
딕셔너리 내부 띄어쓰기 필요해보이네요!~

2022-03-24 07:44 UTC, kyeongraekim commented on jobs/views.py
> +            }
키값이 숫자로 되어있는게 불명확해보이네요!

2022-03-24 07:53 UTC, kyeongraekim requested changes

2022-03-24 07:53 UTC, kyeongraekim commented on jobs/views.py
> +            }
기존 기획으로 다시 변경 부탁드립니다~

2022-03-24 08:59 UTC, wingna1 commented
- sort값 수정 완료
- 전체 공고 수를 리턴하는 total_count가 추가되어 result가 리스트에서 딕셔너리로 변경, 리스트는 list_data에 추가되고 쿼리셋은 슬라이싱되기 전에 리턴된 후 offset과 limit로 슬라이싱되도록 수정

2022-03-24 09:03 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-24 09:03 UTC, merged