[이예솔]Create: users app >> kakao Login, login_decorator
wecode-bootcamp-korea/30-2nd-WantU-backend pull request #4
Opened 2022-03-16 09:27 UTC by wingna1

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인 api
- 로그인 데코레이터

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 프론트에서 access_token을 쿼리 파라미터로 전달받아 카카오 api에 사용자 정보를 요청
- update_or_create 쿼리를 사용해 kakao_id가 존재한다면 닉네임과 프로필 사진을 update하고 존재하지 않는다면 새로 가입
- 가입 후 로그인 혹은 로그인 후 만료 기간 2일짜리 token을 생성, 사용자 정보와 함께 리턴

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-16 09:55 UTC, kyeongraekim requested changes
다음의 내용 확인 후 수정해주세요!~

2022-03-16 09:55 UTC, kyeongraekim commented on users/views.py
> +            "kakao_id"         :user.kakao_id,
kakao_id는 백엔드 선에서 인증/인가 진행을 위해 내부에서 관리할 때 필요한 내용이니 클라이언트 측에 대한 발송이 불필요합니다. 참고해주세요~

2022-03-16 09:55 UTC, kyeongraekim commented on users/views.py
> +        user_information = requests.get(kakao_user_api, headers={"Authorization":f"Bearer ${access_token}"}).json()
requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요. 

예시
```python
class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token    = request.headers['Authorization']
            kakao_user_api_url    = '<https://kapi.kakao.com/v2/user/me>'
            headers     = {"Authorization": f"Bearer ${kakao_access_token}"}

            response = requests.get(kakao_user_api_url, headers = headers, timeout = ..)

2022-03-16 09:55 UTC, kyeongraekim commented on users/views.py
> +class KakaoCallBackView(View):
카카오 로그인의 기능을 담은 내용이오니 클래스 명을 KakaoLoginView 정도로 수정 권장드립니다~

2022-03-16 09:55 UTC, kyeongraekim commented on users/urls.py
> +    path("/kakao/callback", KakaoCallBackView.as_view()),
수정된 클래스명에 맞게 해당 호출명도 바꾸어 주셔야겠네요!~

2022-03-16 11:25 UTC, wingna1 commented on users/views.py
> +        user_information = requests.get(kakao_user_api, headers={"Authorization":f"Bearer ${access_token}"}).json()
중요한 부분이네요 수정했습니다!!

2022-03-16 11:31 UTC, wingna1 commented
수정 완료했습니다.
KeyError에 고민이 좀 있는데요, 맨 처음 access_token이 없는 것과 아래의 user_information이 없는 것을 구분하고 싶은데, 생각하기로는 try ~ except를 따로 받는 것밖에 생각나지 않습니다. 어떻게 해야 할까요?

2022-03-17 02:26 UTC, kyeongraekim requested changes

2022-03-17 02:26 UTC, kyeongraekim commented on users/views.py
> +            user, is_exist = User.objects.update_or_create(
is_exist 보다 created가 더 의미상 맞는 표현 같아 보입니다~ update_or_create 중 업데이트가 아닌 새로운 객체가 생성됬는지 여부를 Boolean 으로 전달하기 때문입니다~

2022-03-17 02:26 UTC, kyeongraekim commented on users/views.py
> +            access_token = request.headers["access_token"]
질문 주신 access_token과 user_information의 차이를 두기 위해서 이곳 access token은 if문으로 에러 핸들링을 하여도 괜찮을 것 같네요!~

2022-03-17 02:32 UTC, wingna1 commented
수정 완료했습니다!
리베이스의 달인이 되어가는 것 같아요

2022-03-17 02:58 UTC, kyeongraekim approved these changes
LGTM!~ 이제 오후에 백엔드 코스 수업 이후, 새롭게 작성해주신 테스트 코드도 add 브랜치로 올려주세요!~

2022-03-17 02:58 UTC, merged