[박영서] Create: s3 upload/download
wecode-bootcamp-korea/30-2nd-WantU-backend pull request #5
Opened 2022-03-16 12:21 UTC by YEONG-CTRL

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 파일을 아마존 s3에 업로드하고, 이를 다운로드 하는 기능을 구현합니다 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. boto를 사용해 client를 정의합니다
2.  post함수에서 클래스에 정의된 client를 불러와, upload_fileobj 메소드를 실행합니다, 이때 클라이언트가 request body에 담아준 파일을 올립니다. 객체의 URL은 DB에 따로 저장합니다
3. get으로 요청이 들어올 경우 기 저장된 URL을 돌려줍니다 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-17 02:56 UTC, kyeongraekim requested changes

2022-03-17 02:56 UTC, kyeongraekim commented on cv/urls.py
> +    path('/uploading', UploadView.as_view()),
RESTful 한 api 설정을 위해서는 POST로 정의되는 동사 형태를 또다른 표현인 upload로 표기하는 것을 지양해주셔야 합니다. 또한 resource  명시를 위해서 이력서에 해당하는 cv나 resume 정도가 URI 로 들어가야 할 것 같네요!~

2022-03-17 02:56 UTC, kyeongraekim commented on cv/views.py
> +class UploadView(View):
관련 s3 버켓을 통해 이력서만을 올린다고 가정했을 시, ResumeUploadView로 보다 명확한 클래스명 표기를 해주시면 좋을 것 같네요!~

2022-03-17 02:56 UTC, kyeongraekim commented on cv/views.py
> +        user_id    = 1
해당 내용이 하드 코딩 되어 있네요? 혹시 로그인 데코레이터가 머지 전이어서 그렇다면 이후에 수정해서 재푸시해주세요!~

2022-03-17 04:43 UTC, kyeongraekim requested changes

2022-03-17 04:43 UTC, kyeongraekim commented on cv/views.py
> +        Resume.objects.create(name = file_name , file_url = file_url, user_id = user_id)
추가로 file에 업로드되는 내용은 파일명이 아닌 uuid로 관리해주시는 것을 권장드립니다. 해당 내용을 한 번 리서치해서 찾아보세요!~

2022-03-17 06:13 UTC, YEONG-CTRL commented on cv/views.py
> +        user_id    = 1
아 이부분은 데코레이터 머지 전이어서 임시 방편으로 해 놓은 부분입니다! 수정하겠습니다

2022-03-17 06:13 UTC, YEONG-CTRL commented on cv/views.py
> +class UploadView(View):
수정하겠습니다!

2022-03-17 06:18 UTC, kyeongraekim commented on cv/views.py
> +        user_id    = 1
넵 영서님~ 실제 실무나가시면 깃헙에서의 머지 무게감이 다르다는 점을 명심해주세요!~ 상용화될 서비스에 실제 코드로서 들어가게 됨으로 하드코딩은 지양해주셔야합니다~

2022-03-17 08:03 UTC, YEONG-CTRL commented on cv/views.py
> +        user_id    = 1
넵 알겠습니다

2022-03-17 08:12 UTC, kyeongraekim requested changes

2022-03-17 08:12 UTC, kyeongraekim commented on cv/views.py
> +class ResumDownloadView(View):
class명에 영문 오타가 있네요!~

2022-03-17 08:12 UTC, kyeongraekim commented on cv/views.py
> +        file       = request.FILES['filename']
해당 키 매핑에 대비해서 에러 핸들링을 해주셔야 될 것 같네요!~

2022-03-17 08:15 UTC, kyeongraekim requested changes

2022-03-17 08:15 UTC, kyeongraekim commented on cv/urls.py
> +    path("/download/<int:resume_pk>", ResumDownloadView.as_view())
다시 한 번, 동사는 http method로 의미 전달이 충분합니다 URI 명시방법을 다시 한 번 고민해주세요~

2022-03-17 11:20 UTC, YEONG-CTRL commented on cv/urls.py
> +    path("/download/<int:resume_pk>", ResumDownloadView.as_view())
넵 REST하게 수정하고 통신 확인했습니다!

2022-03-18 01:39 UTC, kyeongraekim approved these changes
LGTM!~ 이제 해당 기능에 대한 테스트 코드 새로운 브랜치로 푸시해주세요!~

2022-03-18 01:39 UTC, merged