S3 Feature Unit Test
wecode-bootcamp-korea/30-2nd-WantU-backend pull request #8
Opened 2022-03-18 07:17 UTC by YEONG-CTRL

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- s3 upload/download 브랜치의 기능을 unittest하는 것이 목표입니다
-
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. upload/ download view에 따라 다른 클래스 생성
2. setUp메소드에 임시로 사용할 DB생성
3. 이때 로그인 데코레이터를 통과하기 위한 임의의 토큰 생성 
4. unit test를 진행하돼, request.FILE에 맞게 파일을 넘겨주기 위하여 SimpleUploadedFile 사용

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- request.FILE은 단순히 json으로 처리해 주는 것이 아니라, 파일 형식에 맞게 값을 제공해야 한다는 것을 알게 됐습니다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-03-18 07:52 UTC, kyeongraekim requested changes

2022-03-18 07:52 UTC, kyeongraekim commented on cv/tests.py
> +                'message' : 'upload succeed'
upload_succeeded나 upload_success 정도가 더 올바론 표현 같네요!~ 제 3자를 위해 올바른 영문법도 늘 신경써주세요~ ㅎㅎ

2022-03-18 07:52 UTC, kyeongraekim commented on cv/tests.py
> +        self.assertEqual(response.status_code, 200)
post success 이니 create의 느낌이겠네요? View 와 테스트 코드 모두 상태 코드 201로 정도로 변경해주세요~

2022-03-18 07:52 UTC, kyeongraekim commented on cv/tests.py
> +    def setUp(self):
장고에서는 테스트용 메소드로 setUp외에 setUpTestData라는 것도 있습니다. 둘의 차이를 비교해보고 해당 테스트 코드에서 어떠한 내용을 사용하는 것이 나을지 한 번 고민해보세요!~ 그리고 결정사항을 아래 코멘트로 남겨주세요~

2022-03-18 07:52 UTC, kyeongraekim commented on cv/tests.py
> +    def test_ResumeUploadView_post_Key_error(self):
테스트 코드 함수명은 test_fail.. test_success.. 정도로 처음 시작을 진행해주셔서 보다 명확하게 함수명을 짜주세요! 그리고 post_key_error 보다 정확히 어떠한 키매핑 상황에서 일으킨 에러인지를 명시해주세요~

2022-03-18 07:52 UTC, kyeongraekim commented on cv/tests.py
> +        self.assertEqual(response.status_code, 200)
성공 테스트외에 실패 테스트도 꼭 넣어주셔야 하는데 View에 일단 아무런 에러핸들링이 안되어있는채로 올라왔군요! 다음 푸시 때 View 도 한 번 발생가능한 에러를 추가해서 테스트코드에 반영 후 올려주세요!~

2022-03-18 08:31 UTC, YEONG-CTRL commented on cv/tests.py
> +    def setUp(self):
setUpTestData의 경우 TestCase 클래스 하나에 초기의 테스트 데이터를 만들고, 이를 지속시키기에 setUp의 경우처럼 매 테스트 메서드가 호출 될 때마다 테스트 데이터셋을 준비할 필요가 없어 성능 향상의 이점이 있는 듯 합니다. 다만 transaction을 지원하지 않는 db(mysql엔진이 MyISAM인 경우)에는 setUp과 마찬가지로 각 테스트 메서드 이전에 호출되기에 이점이 없는 듯합니다. 그러나 제가 사용하는 프로젝트의 DB엔진은 트랜잭션을 지원하는 INNODB이므로 
<img width="705" alt="image" src="https://user-images.githubusercontent.com/79896709/158963855-15fff31d-009a-4441-8525-f910f9c8609a.png"> 트랜젝션을 지원하기에 setUPTestData를 사용하는 것이 성능에 좋습니다.
또한 teardown을 명시할 필요없이 TestCase 클래스가 다 실행되면 DB가 원상복구 되는 것도 장점입니다. 
제 unit test에는 처음에 형성된 데이터가 test 실행중간에 변경될 필요가 없고 초기 생성된 데이터를 쭉 사용하면 되기에 시간적 이점이 있는 setUpTestData를 사용하려 합니다.

2022-03-18 09:16 UTC, YEONG-CTRL commented on cv/tests.py
> +                'message' : 'upload succeed'
수정했습니다

2022-03-18 09:17 UTC, YEONG-CTRL commented on cv/tests.py
> +        self.assertEqual(response.status_code, 200)
패스 파라미터로 없는 값이 올라왔을때 에러 핸들링 하는 코드 추가했습니다

2022-03-20 03:54 UTC, kyeongraekim approved these changes
LGTM!~ 다음 맡은 기능 이어서 진행해주세요!~

2022-03-20 03:54 UTC, merged